on: push
name: Publish Website
jobs:
  web-deploy:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: get latest code
      uses: actions/checkout@v2.3.2

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_NAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/
        exclude: .git*
          - .git*/**
          -  **/.git*/**
          - */_drafts
          - */source
          - .lnk
          - .config.codekit3
          - README.md
