on: push
name: Publish Website
jobs:
  web-deploy:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: get latest code
      uses: actions/checkout@v2.1.0

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_NAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/
